version: '3.9'
services:
  login_api:
    container_name: news_login_api
    build: ./
    image: go_news_login_api:1.0.0
    ports:
      - "7700:7700"
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./env/:/app/env:Z