package totp

import (
	"github.com/xlzd/gotp"
	"time"
)

// Verify otp generated by GAuthenticator against Generated based on secretKey of user
func Verify(secret string, otp string) bool {
	// get OTP based on secret
	totp := gotp.NewDefaultTOTP(secret)
	// verify otp from user device and compare with generated for current timestamp
	return totp.Verify(otp, time.Now().Unix())
}

func GenerateSecret() string {
	return gotp.RandomSecret(16)
}
