version: '3.9'
name: news
services:
  login_api:
    container_name: news_login_api
    image: go_news_login_api:1.0.1
    ports:
      - "7700:7700"
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./env/:/app/env:Z
